In [27]:
import pandas as pd

arquivo = 'http://www.harve.com.br/praticas/dados_etl.csv'
df = pd.read_csv(arquivo, sep = "\t")

In [7]:
df['Name'] = 'josé'
print(df['Name'])

0       josé
1       josé
2       josé
3       josé
4       josé
        ...
2235    josé
2236    josé
2237    josé
2238    josé
2239    josé
Name: Name, Length: 2240, dtype: object

In [8]:
df.dtypes

Client ID                int64
Year_Birth               int64
Education               object
Marital_Status          object
Income                 float64
Kidhome                  int64
Teenhome                 int64
Dt Customer             object
Recency                  int64
MntWines                 int64
MntFruits                int64
MntMeatProducts          int64
MntFishProducts          int64
MntSweetProducts         int64
MntGoldProds             int64
NumDealsPurchases        int64
NumWebPurchases          int64
NumCatalogPurchases      int64
NumStorePurchases        int64
NumWebVisitsMonth        int64
AcceptedCmp3             int64
AcceptedCmp4             int64
AcceptedCmp5             int64
AcceptedCmp1             int64
AcceptedCmp2             int64
Complain                 int64
Z_CostContact            int64
Z_Revenue                int64
Response                 int64
Name                    object
dtype: object

In [9]:
print(df['Year_Birth'])

0       1957
1       1954
2       1965
3       1984
4       1981
        ...
2235    1967
2236    1946
2237    1981
2238    1956
2239    1954
Name: Year_Birth, Length: 2240, dtype: int64

In [10]:
df['Age'] = 2026 - df['Year_Birth']
print(df['Age'])

0       69
1       72
2       61
3       42
4       45
        ..
2235    59
2236    80
2237    45
2238    70
2239    72
Name: Age, Length: 2240, dtype: int64

In [11]:
dfPromocao = df[df['Age'] > 50]
print(dfPromocao)

      Client ID  Year_Birth   Education Marital_Status   Income  Kidhome  \
0          5524        1957  Graduation         Single  58138.0        0
1          2174        1954  Graduation         Single  46344.0        1
2          4141        1965  Graduation       Together  71613.0        0
5          7446        1967      Master       Together  62513.0        0
6           965        1971  Graduation       Divorced  55635.0        0
...         ...         ...         ...            ...      ...      ...
2234       8372        1974  Graduation        Married  34421.0        1
2235      10870        1967  Graduation        Married  61223.0        0
2236       4001        1946         PhD       Together  64014.0        2
2238       8235        1956      Master       Together  69245.0        0
2239       9405        1954         PhD        Married  52869.0        1

      Teenhome Dt Customer  Recency  MntWines  ...  AcceptedCmp4  \
0            0  04-09-2012       58       635  ...             0
1            1  08-03-2014       38        11  ...             0
2            0  21-08-2013       26       426  ...             0
5            1  09-09-2013       16       520  ...             0
6            1  13-11-2012       34       235  ...             0
...        ...         ...      ...       ...  ...           ...
2234         0  01-07-2013       81         3  ...             0
2235         1  13-06-2013       46       709  ...             0
2236         1  10-06-2014       56       406  ...             0
2238         1  24-01-2014        8       428  ...             0
2239         1  15-10-2012       40        84  ...             0

      AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  Z_CostContact  \
0                0             0             0         0              3
1                0             0             0         0              3
2                0             0             0         0              3
5                0             0             0         0              3
6                0             0             0         0              3
...            ...           ...           ...       ...            ...
2234             0             0             0         0              3
2235             0             0             0         0              3
2236             0             1             0         0              3
2238             0             0             0         0              3
2239             0             0             0         0              3

      Z_Revenue  Response  Name  Age
0            11         1  josé   69
1            11         0  josé   72
2            11         0  josé   61
5            11         0  josé   59
6            11         0  josé   55
...         ...       ...   ...  ...
2234         11         0  josé   52
2235         11         0  josé   59
2236         11         0  josé   80
2238         11         0  josé   70
2239         11         1  josé   72

[1545 rows x 31 columns]

In [12]:
import pandas as pd

# Carregar o arquivo (o separador é tabulação)
df_clientes = pd.read_csv('http://www.harve.com.br/praticas/dados_etl.csv', sep='\t')

# 1. Criar coluna com a quantidade total de filhos (Crianças + Adolescentes)
df_clientes['Total_Filhos'] = df_clientes['Kidhome'] + df_clientes['Teenhome']

# 2. Criar coluna com a quantidade total de vendas (Soma de todos os canais de compra)
df_clientes['Total_Vendas'] = (
    df_clientes['NumDealsPurchases'] +
    df_clientes['NumWebPurchases'] +
    df_clientes['NumCatalogPurchases'] +
    df_clientes['NumStorePurchases']
)

# Exibir o resultado para conferência
colunas_para_visualizar = ['Client ID', 'Total_Filhos', 'Total_Vendas']
print(df_clientes[colunas_para_visualizar].head())

   Client ID  Total_Filhos  Total_Vendas
0       5524             0            25
1       2174             2             6
2       4141             0            21
3       6182             1             8
4       5324             1            19

In [13]:
df['Education'].value_counts()

Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

In [14]:
ensino_dict = {
    'Graduation': 'MID',
    'PhD': 'HIGH',
    'Master': 'HIGH',
    '2n Cycle': 'LOW',
    'Basic': 'MID'
}

In [15]:
df.isna() .sum()

Client ID               0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
Name                    0
Age                     0
dtype: int64

In [16]:
tmp = df[df.Income.isna() == True]
print(len(tmp))

24

In [17]:
import pandas as pd

# ============================================================
# EXTRAÇÃO
# ============================================================
df_titanic = pd.read_csv('https://www.harve.com.br/praticas/titanic-pt-BR.csv')

print("=" * 55)
print("EXTRAÇÃO")
print("=" * 55)
print(f"Registros carregados: {len(df_titanic)}")
print(f"\nValores nulos por coluna:\n{df_titanic.isnull().sum()}")

=======================================================
EXTRAÇÃO
=======================================================
Registros carregados: 891

Valores nulos por coluna:
Id do passageiro          0
Sobrevivente              0
Classe                    0
Nome                      0
Sexo                      0
Idade                   177
Irmaos ou conjuge         0
Pais ou filhos            0
Ticket                    0
Tarifa do passageiro      0
Cabine                  687
Local de embarque         2
dtype: int64

In [18]:
# ============================================================
# TRANSFORMAÇÃO — Desafio 1
# ============================================================
print("\n" + "=" * 55)
print("TRANSFORMAÇÃO — Desafio 1: Local de embarque")
print("=" * 55)

# Registros sem local de embarque
sem_embarque = df_titanic[df_titanic['Local de embarque'].isnull()]
print(f"\nRegistros sem local de embarque ({len(sem_embarque)}):")
print(sem_embarque[['Id do passageiro', 'Nome', 'Local de embarque']])

# Excluir registros sem local de embarque
df_titanic = df_titanic.dropna(subset=['Local de embarque'])
print(f"\nRegistros após exclusão: {len(df_titanic)}")
print(f"Nulos em 'Local de embarque': {df_titanic['Local de embarque'].isnull().sum()}")

=======================================================
TRANSFORMAÇÃO — Desafio 1: Local de embarque
=======================================================

Registros sem local de embarque (2):
     Id do passageiro                                       Nome  \
61                 62                        Icard, Miss. Amelie
829               830  Stone, Mrs. George Nelson (Martha Evelyn)

    Local de embarque
61                NaN
829               NaN

Registros após exclusão: 889
Nulos em 'Local de embarque': 0

In [19]:
# ============================================================
# TRANSFORMAÇÃO — Desafio 1 (continuação)
# ============================================================
print("\n" + "=" * 55)
print("TRANSFORMAÇÃO — Desafio 1: Idade nula → média")
print("=" * 55)

idades_nulas_antes = df_titanic['Idade'].isnull().sum()
media_idade = df_titanic['Idade'].mean()
print(f"Idades nulas antes: {idades_nulas_antes}")
print(f"Média de idade calculada: {media_idade:.2f}")

df['Idade'] = df_titanic['Idade'].fillna(media_idade)

print(f"Idades nulas após preenchimento: {df_titanic['Idade'].isnull().sum()}")

=======================================================
TRANSFORMAÇÃO — Desafio 1: Idade nula → média
=======================================================
Idades nulas antes: 177
Média de idade calculada: 29.64
Idades nulas após preenchimento: 177

In [20]:
# ============================================================
# TRANSFORMAÇÃO — Desafio 2: Categorização por idade
# ============================================================
print("\n" + "=" * 55)
print("TRANSFORMAÇÃO — Desafio 2: Categoria de idade")
print("=" * 55)

def categorizar_idade(idade):
    if idade <= 10:
        return 'Criança'
    elif idade <= 20:
        return 'Joven'
    elif idade <= 60:
        return 'Adulto'
    else:
        return 'Idoso'

df_titanic['Categoria de Idade'] = df_titanic['Idade'].apply(categorizar_idade)

print("\nContagem por categoria (value_counts):")
print(df_titanic['Categoria de Idade'].value_counts())

=======================================================
TRANSFORMAÇÃO — Desafio 2: Categoria de idade
=======================================================

Contagem por categoria (value_counts):
Categoria de Idade
Adulto     512
Idoso      198
Joven      115
Criança     64
Name: count, dtype: int64

In [21]:
# ============================================================
# CARGA
# ============================================================
print("\n" + "=" * 55)
print("CARGA")
print("=" * 55)

output_path = 'titanic_transformado.csv'
df.to_csv(output_path, index=False, encoding='utf-8-sig')
print(f"Arquivo salvo em: {output_path}")
print(f"Total de registros exportados: {len(df_titanic)}")
print(f"\nPrimeiras linhas do resultado:")
print(df_titanic[['Id do passageiro', 'Nome', 'Idade', 'Local de embarque', 'Categoria de Idade']].head(5))

=======================================================
CARGA
=======================================================
Arquivo salvo em: titanic_transformado.csv
Total de registros exportados: 889

Primeiras linhas do resultado:
   Id do passageiro                                               Nome  Idade  \
0                 1                            Braund, Mr. Owen Harris   22.0
1                 2  Cumings, Mrs. John Bradley (Florence Briggs Th...   38.0
2                 3                             Heikkinen, Miss. Laina   26.0
3                 4       Futrelle, Mrs. Jacques Heath (Lily May Peel)   35.0
4                 5                           Allen, Mr. William Henry   35.0

  Local de embarque Categoria de Idade
0       Southampton             Adulto
1         Cherbourg             Adulto
2       Southampton             Adulto
3       Southampton             Adulto
4       Southampton             Adulto

In [22]:
import pandas as pd

# ============================================================
# EXTRAÇÃO
# ============================================================
df_netflix = pd.read_csv('http://www.harve.com.br/praticas/NetflixViewingHistory.csv')

print("=" * 55)
print("EXTRAÇÃO")
print("=" * 55)
print(f"Registros carregados: {len(df_netflix)}")
print(f"\nPrimeiras linhas:")
print(df_netflix.head())

# ============================================================
# TRANSFORMAÇÃO
# ============================================================

# --- Converter coluna Date para datetime ---
df_netflix['Date'] = pd.to_datetime(df_netflix['Date'], dayfirst=True)

# ============================================================
# Desafio 1: Quantos são filmes e quantos são séries?
# Lógica: títulos com ':' no nome são séries, sem ':' são filmes
# ============================================================
print("\n" + "=" * 55)
print("DESAFIO 1: Filmes vs Séries")
print("=" * 55)

df_netflix['Tipo'] = df_netflix['Title'].apply(
    lambda titulo: 'Série' if ':' in titulo else 'Filme'
)

contagem_tipo = df_netflix['Tipo'].value_counts()
print(f"\nContagem por tipo:")
print(contagem_tipo)

total = len(df_netflix)
for tipo, qtd in contagem_tipo.items():
    print(f"  {tipo}: {qtd} ({qtd/total*100:.1f}%)")

# ============================================================
# Desafio 2: Dia da semana com mais e menos visualizações
# 0: Segunda  1: Terça  2: Quarta  3: Quinta
# 4: Sexta    5: Sábado  6: Domingo
# ============================================================
print("\n" + "=" * 55)
print("DESAFIO 2: Dia da semana")
print("=" * 55)

dias_semana = {
    0: 'Segunda',
    1: 'Terça',
    2: 'Quarta',
    3: 'Quinta',
    4: 'Sexta',
    5: 'Sábado',
    6: 'Domingo'
}

df_netflix['Dia da Semana Num'] = df_netflix['Date'].dt.dayofweek
df_netflix['Dia da Semana']     = df_netflix['Dia da Semana Num'].map(dias_semana)

views_por_dia = df_netflix['Dia da Semana'].value_counts()
views_por_dia_pct = df_netflix['Dia da Semana'].value_counts(normalize=True) * 100

dia_mais  = views_por_dia.idxmax()
dia_menos = views_por_dia.idxmin()

print(f"\nVisualizações por dia da semana:")
for dia in dias_semana.values():
    qtd = views_por_dia.get(dia, 0)
    pct = views_por_dia_pct.get(dia, 0)
    print(f"  {dia:<10}: {qtd:>3} visualizações ({pct:.1f}%)")

print(f"\n✅ Dia com MAIS  visualizações: {dia_mais}  ({views_por_dia[dia_mais]} | {views_por_dia_pct[dia_mais]:.1f}%)")
print(f"✅ Dia com MENOS visualizações: {dia_menos} ({views_por_dia[dia_menos]} | {views_por_dia_pct[dia_menos]:.1f}%)")

# ============================================================
# CARGA
# ============================================================
print("\n" + "=" * 55)
print("CARGA")
print("=" * 55)

output_path = 'netflix_transformado.csv'
df_netflix.to_csv(output_path, index=False, encoding='utf-8-sig')
print(f"Arquivo salvo em: {output_path}")
print(f"Total de registros exportados: {len(df_netflix)}")
print(f"\nColunas finais: {list(df_netflix.columns)}")

=======================================================
EXTRAÇÃO
=======================================================
Registros carregados: 311

Primeiras linhas:
                         Title        Date
0   Dentro da Mente de um Gato  23/08/2022
1           A Estrela de Belém  05/08/2022
2                     La Bamba  24/07/2022
3  Arremesso Final: Episódio 3  17/07/2022
4  Arremesso Final: Episódio 2  17/07/2022

=======================================================
DESAFIO 1: Filmes vs Séries
=======================================================

Contagem por tipo:
Tipo
Série    257
Filme     54
Name: count, dtype: int64
  Série: 257 (82.6%)
  Filme: 54 (17.4%)

=======================================================
DESAFIO 2: Dia da semana
=======================================================

Visualizações por dia da semana:
  Segunda   :   5 visualizações (1.6%)
  Terça     :  14 visualizações (4.5%)
  Quarta    :  13 visualizações (4.2%)
  Quinta    :  19 visualizações (6.1%)
  Sexta     :  37 visualizações (11.9%)
  Sábado    : 107 visualizações (34.4%)
  Domingo   : 116 visualizações (37.3%)

✅ Dia com MAIS  visualizações: Domingo  (116 | 37.3%)
✅ Dia com MENOS visualizações: Segunda (5 | 1.6%)

=======================================================
CARGA
=======================================================
Arquivo salvo em: netflix_transformado.csv
Total de registros exportados: 311

Colunas finais: ['Title', 'Date', 'Tipo', 'Dia da Semana Num', 'Dia da Semana']

In [23]:
df_netflix.dtypes

Title                        object
Date                 datetime64[ns]
Tipo                         object
Dia da Semana Num             int32
Dia da Semana                object
dtype: object

In [24]:
print(df_netflix['Date'])

0     2022-08-23
1     2022-08-05
2     2022-07-24
3     2022-07-17
4     2022-07-17
         ...
306   2020-12-05
307   2020-12-05
308   2020-12-05
309   2020-12-05
310   2020-12-05
Name: Date, Length: 311, dtype: datetime64[ns]

In [25]:
print(df_netflix[['Date','Title']])

          Date                                         Title
0   2022-08-23                    Dentro da Mente de um Gato
1   2022-08-05                            A Estrela de Belém
2   2022-07-24                                      La Bamba
3   2022-07-17                   Arremesso Final: Episódio 3
4   2022-07-17                   Arremesso Final: Episódio 2
..         ...                                           ...
306 2020-12-05                     Tudo Bem No Natal Que Vem
307 2020-12-05  Explicando - A Mente: Temporada 1: Meditação
308 2020-12-05  Explicando - A Mente: Temporada 1: Ansiedade
309 2020-12-05     Explicando - A Mente: Temporada 1: Sonhos
310 2020-12-05    Explicando - A Mente: Temporada 1: Memória

[311 rows x 2 columns]

In [26]:
print(df_netflix)

                                            Title       Date   Tipo  \
0                      Dentro da Mente de um Gato 2022-08-23  Filme
1                              A Estrela de Belém 2022-08-05  Filme
2                                        La Bamba 2022-07-24  Filme
3                     Arremesso Final: Episódio 3 2022-07-17  Série
4                     Arremesso Final: Episódio 2 2022-07-17  Série
..                                            ...        ...    ...
306                     Tudo Bem No Natal Que Vem 2020-12-05  Filme
307  Explicando - A Mente: Temporada 1: Meditação 2020-12-05  Série
308  Explicando - A Mente: Temporada 1: Ansiedade 2020-12-05  Série
309     Explicando - A Mente: Temporada 1: Sonhos 2020-12-05  Série
310    Explicando - A Mente: Temporada 1: Memória 2020-12-05  Série

     Dia da Semana Num Dia da Semana
0                    1         Terça
1                    4         Sexta
2                    6       Domingo
3                    6       Domingo
4                    6       Domingo
..                 ...           ...
306                  5        Sábado
307                  5        Sábado
308                  5        Sábado
309                  5        Sábado
310                  5        Sábado

[311 rows x 5 columns]